services:
  database: 
    image: postgres:17.6
    container_name: postgres-db
    environment: 
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - ${PGPORT}:5432 #puerto del host contenedor a maquina local:puerto dentro del container
    volumes:
      - ./database:/var/lib/postgresql/data